# Generated by Django 5.2.5 on 2025-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="available_quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="ordered_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
