# Generated by Django 5.2.5 on 2025-09-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_order_customer_order_payment_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="customer",
        ),
    ]
