# Generated by Django 5.2.5 on 2025-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Në pritje"),
                    ("confirmed", "E konfirmuar"),
                    ("shipped", "E dërguar"),
                    ("delivered", "Përfunduar"),
                    ("canceled", "Anulluar"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
