# Generated by Django 5.2.5 on 2025-09-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
