# Generated by Django 5.2.5 on 2025-09-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
    ]
