# Generated by Django 5.2.5 on 2025-09-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_ordernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
