# Generated by Django 5.2.5 on 2025-09-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
