# Generated by Django 5.2.5 on 2025-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Në përgatitje"),
                    ("shipped", "E dërguar"),
                    ("delivered", "Përfunduar"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
